# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod Properties
mod_version=0.1+1.21.1
maven_group=io.github.foundationgames
archives_base_name=splinecart

# Dependencies
neoforge_version = 21.1.125
parchment_version = 2024.11.17